[package]
name = "scadm"
version = "0.1.0"
edition = "2021"

[dependencies]
p4rs = { git = "https://github.com/oxidecomputer/p4", branch = "main" }
#p4rs = { path = "/home/ry/src/p4/lang/p4rs" }
p9ds = { git = "https://github.com/oxidecomputer/p9fs" }
p9kp = { git = "https://github.com/oxidecomputer/p9fs" }
devinfo = { git = "https://github.com/oxidecomputer/devinfo-sys" }
base64 = { version = "0.13" }
clap = { version = "4", features = ["derive"] }
libc = "0.2"
serde = "1.0"
serde_json = "1.0"
slog = "2.7"
slog-term = "2.7"
slog-async = "2.7"
slog-envlogger = "2.2"
tokio = { version = "1", features = ["full"] }
indicatif = "0.17"
errno = "0.2"
num = { version = "0.4.0", features = ["num-bigint"] }

[dependencies.softnpu] 
git = "https://github.com/oxidecomputer/softnpu"
branch = "main"
